task_name: dict_scigen
path: /netscratch/borisova/TableEval/data/SciGen/scigen_merged_updated_2025-02-13
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
instruction: ""
doc_to_text: 'Your task is to generate textual description for the given table. The summary must describe the most important findings reported in table by reasoning over its content. The text should be coherent. Table: {"table_caption": {{table_caption}},  "table_column_names": {{table_column_names}}, "table_content_values": {{table_content_values}} }.'
doc_to_target: text_cleaned
metric_list:
  - bleu
  - meteor
  - bertS
  - bleurt
