task_name: image_scigen
path: /netscratch/borisova/TableEval/data/SciGen/scigen_merged_updated_2025-01-23
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
instruction: ""
doc_to_text: !function image_parser.parse
doc_to_target: text
multi_modal_data: True
metric_list:
  - bleu
  - meteor
    #  - moverS
  - bertS
  - bleurt
