task_name: xml_scigen
path: /netscratch/user/TableEval/data/SciGen/scigen_updated_2025-03-07
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
save_columns: instance_id,image_id,paper_id
ignore_columns: table_xml_cleaned 
instruction: ""
doc_to_text: 'Describe the given table focusing on the most important findings reported by reasoning over its content. The summary must be factual, coherent, and well-written. Do not introduce new information or speculate. Table: {{table_xml_cleaned}}'
doc_to_target: text_cleaned
metric_list:
  #- perplexity
  - sacrebleu
  - moverS
  - meteor
  - bertS
  - bleurt
  - bleu1
  - bleu2
  - bleu3
  - bleu4
  - rougeL
  - rougeLsum
  - rouge1
  - rouge2
  - rouge3
  - rouge4