task_name: html_logic2text
path: /netscratch/borisova/TableEval/data/Logic2Text/logic2text_updated_2025-02-23
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
instruction: ""
doc_to_text: 'Generate a one sentence statement based on the table and logical form. Logical form: {{logic_str}}. Table title: {{title}}. Table: {{table_html}}.'
doc_to_target: sent
metric_list:
  - bleu
  - rouge1
  - rogue2
  - rogueL

