task_name: image_numericnlg
path: /netscratch/borisova/TableEval/data/numericNLG/numericnlg_updated_2025-01-23
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
instruction: ""
doc_to_text: !function image_parser.parse
doc_to_target: description
metric_list:
  - bleu
  - rougeL
  - meteor
