task_name: latex_numericnlg
path: /netscratch/borisova/TableEval/data/numericNLG/numericnlg_updated_2024-12-27
test_split: test
validation_split: validation
train_split: train
num_fewshot: 2
instruction: "generate a brief description of the following table:\n"
doc_to_text: "{{table_latex}}\ndescription:"
doc_to_target: description
metric_list:
  - bleu
  - rougeL 
  - meteor

