task_name: xml_numericnlg
path: /netscratch/borisova/TableEval/data/numericNLG/numericnlg_updated_2025-03-07
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
save_columns: instance_id,table_id_paper,table_id,paper_id,image_id
instruction: ""
doc_to_text: 'Describe the given table focusing on the insights and trends revealed by the results. The summary must be factual, coherent, and well-written. Do not introduce new information or speculate. Table: {{table_xml}}.'
doc_to_target: description
metric_list:
  #- perplexity
  - sacrebleu
  - moverS
  - meteor
  - bertS
  - bleurt
  - bleu1
  - bleu2
  - bleu3
  - bleu4
  - rougeL
  - rougeLsum
  - rouge1
  - rouge2
  - rouge3
  - rouge4