task_name: dict_logicnlg
path: /netscratch/borisova/TableEval/data/LogicNLG/logicnlg_filtered_merged_ref_updated_2025-01-24
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
instruction: ""
doc_to_text: 'Based on a given table, fill in the entity masked by [ENT] in the following sentence: {{template}}. Output the sentence with filled in masked entities. Table: {"title": {{title}}, "table column names": {{table_column_names}}, "table content values": {{table_content_values}}}'
doc_to_target: ref
metric_list:
  - perplexity
  - bleu
