task_name: image_logicnlg
path: /netscratch/borisova/TableEval/data/LogicNLG/logicnlg_updated_2025-03-07
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
save_columns: instance_id,image_name,filename,table_id,topic,title
instruction: ""
doc_to_text: !function image_parser.parse 
doc_to_target: ref
multi_modal_data: True
metric_list:
  #- perplexity
  - sacrebleu
  - moverS
  - meteor
  - bertS
  - bleurt
  - bleu1
  - bleu2
  - bleu3
  - bleu4
  - rougeL
  - rougeLsum
  - rouge1
  - rouge2
  - rouge3
  - rouge4