task_name: image_logicnlg
path: /netscratch/borisova/TableEval/data/LogicNLG/logicnlg_updated_2025-02-23
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
instruction: ""
doc_to_text: !function image_parser.parse 
doc_to_target: ref
multi_modal_data: True
metric_list:
  #- perplexity
  - bleurt
  - bertS
  - bleu1
  - bleu2
  - bleu3
  - bleu4
  - rougeL
  - rouge1
  - rouge2
  - rouge3 
  - meteor
