task_name: dict_comtqa_pmc
path: /netscratch/borisova/TableEval/data/ComTQA_data/comtqa_pmc_updated_2025-03-06
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
instruction: ""
doc_to_text: 'Refer to the provided table and answer the question. Question: {{question}}. Table title: {{table_title}}. Table: {"table_caption": {{table_caption}}, "table_headers": {{table_headers}}, "table_subheaders": {{table_subheaders}}, "table_rows": {{table_rows}}, "table_footnote": {{table_footnote}}}.'
doc_to_target: answer
metric_list:
  #- perplexity
  #- sacrebleu
  #- moverS
  - bleurt
  - bertS
  - bleu1
  - bleu2
  - bleu3
  - bleu4
  - meteor
  - rougeL
  - rouge1
  - rouge2
  - rouge4
