task_name: html_comtqa_pmc
path: /netscratch/borisova/TableEval/data/ComTQA_data/comtqa_pmc_2025-02-28
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
instruction: ""
doc_to_text: 'Refer to the provided table and answer the question. Question: {{question}}. Table: {{table_html}}.'
doc_to_target: answer
metric_list:
  #- perplexity
  #- sacrebleu
  #- moverS
  - bleurt
  - bertS
  - bleu1
  - bleu2
  - bleu3
  - bleu4
  - meteor
  - rougeL
  - rouge1
  - rouge2
  - rouge4

