task_name: image_comtqa_pmc
path: /netscratch/borisova/TableEval/data/ComTQA_data/comtqa_pmc_2025_01_23
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
instruction: ""
doc_to_text: !function image_parser.parse
doc_to_target: answer
metric_list:
  - accuracy
  - f1
  - bleu
  - rougeL
  - meteor
