task_name: dict_comtqa_fin
path: /netscratch/borisova/TableEval/data/ComTQA_data/comtqa_fin_updated_2025-03-13
test_split: test
validation_split: validation
train_split: test
num_fewshot: 0
save_columns: instance_id,table_id,image_name
instruction: ""
doc_to_text:  'Refer to the provided table and answer the question. Question: {{question}}. Table: {"table_headers": {{table_headers}}, "table_rows": {{table_rows}}}.'
doc_to_target: answer
metric_list:
  #- perplexity
  - accuracy
  - f1
  - sacrebleu
  - moverS
  - meteor
  - bertS
  - bleurt
  - bleu1
  - bleu2
  - bleu3
  - bleu4
  - rougeL
  - rougeLsum
  - rouge1
  - rouge2
  - rouge3
  - rouge4
 
